### ISSUE TITLE
What does this error really mean `invalid content line value`?

### ISSUE THREAD

**Issue by leedstyh** [MJKWoolnough/ics#3]
Got this error while decoding from a URL, but not sure how to fix it!

**Comment by MJKWoolnough** [comment]
It would indicate that the value part (after the ':') of one of the lines the lines either contains an invalid character or doesn't end with CRLF/EOF.

The safe characters are defined in the [spec](https://tools.ietf.org/html/rfc5545#page-11), and the corresponding unsafe chars are defined in [tokeniser.go](https://github.com/MJKWoolnough/ics/blob/master/tokeniser.go#L22), up to the new line for this case, so ';', ':' and ',' are all allowed.

Are you able to share the URL? If there's no invalid character it may be a fault with the tokeniser.

**Comment by leedstyh** [comment]
Sure, this is my testing code:

```
package main

import (
	"log"
	"net/http"

	"github.com/MJKWoolnough/ics"
)

func main() {
	var icalUrl = "https://www.formula1.com/sp/static/f1/2018/calendar/ical.ics"
	// var icalUrl = "https://www.stanza.co/api/schedules/acmilan/acmilan.ics"

	resp, err := http.Get(icalUrl)
	if err != nil {
		log.Fatalln(1, err.Error())
	}
	defer resp.Body.Close()

	cal, err := ics.Decode(resp.Body)
	if err != nil {
		log.Fatalln(2, err.Error()) // Got error here
	}

	for i := range cal.Event {
		log.Println(string(cal.Event[i].Summary.Text))
	}
}
```

And my OS is windows 10 64bit, go version is 1.9.1

**Comment by MJKWoolnough** [comment]
OK, the problem is that both of the calendar files violate the spec; neither of them terminate lines with CRLF, just LF.

You'll need to convert between the two. I've written a [package](https://github.com/MJKWoolnough/dos2unix) that will help with that. Add the import and replace the Decode line with the following:

`cal, err := ics.Decode(dos2unix.Unix2DOS(bufio.NewReader(resp.Body)))`

That now works on my end.

**Comment by leedstyh** [comment]
Thank you for the quick fix, and a great package.

**Comment by leedstyh** [comment]
Oops, the second URL (acmilan) got another error: `invalid encoded text`

**Comment by MJKWoolnough** [comment]
The second also violates the spec, this time by using a non-safe char, a [comma without escaping](https://tools.ietf.org/html/rfc5545#page-46). I can't see an easy fix for this one.

You could fork the package and remove the comma from [line 1080 of types.go](https://github.com/MJKWoolnough/ics/blob/master/types.go#L1080), or just make the change on your local copy if this is a personal project.

You could always ask the author of the calendar files to fix them.

**Comment by leedstyh** [comment]
Thank you @MJKWoolnough !
