### ISSUE TITLE
Google Calendar ICS is invalid

### ISSUE THREAD

**Issue by acomagu** [MJKWoolnough/ics#4]
Google Calendar ICS can include `ACTION:NONE` line in ALARM section.

It's invalid so this library returns error(ErrMissingAlarmAction), but Google Calendar is really popular so maybe it should be accepted?

ref. https://github.com/C4ptainCrunch/ics.py/pull/143

~~Fortunately this issue can be avoided easily by replacing `ACTION:NONE` with `ACTION:DISPLAY`(or other action type). I don't know which is the better way to solve this, do you have any idea about this?~~

**Comment by MJKWoolnough** [comment]
I've just added support for `ACTION:NONE` (ab71f213aa9266c828d626d6944147db0953eed0), as well as a bunch of other proposed, but not currently standard, VALARM properties.

**Comment by acomagu** [comment]
Thank you for your work! :nerd_face:
